#!/usr/bin/env python3
"""Export the HealthBench-Psych v1.0.0 rubric as an `instrument.v1` artifact --
the thing this benchmark's verdicts are cast AGAINST.

Third exporter of the platform seam, and the one that closes the keying hole
the other two work around:

  export_platform_artifacts.py  AGGREGATES (`mindbench-results.v1`) -- one panel
                                mean per candidate model.
  export_ledger_batch.py        PER-CALL EVIDENCE (`generation-batch.v1`) --
                                every response, every rubric-item verdict.
  this script                   THE INSTRUMENT (`instrument.v1`) -- the 7,034
                                rubric criteria those verdicts answer, each
                                under the SAME `item_key` the batch writes.

WHY IT EXISTS. `assessment.v1` rows name an instrument by
(project_slug, kind, version) plus an `item_key`, and the platform's
`instrumentRefs.instrumentFor` REFUSES a named instrument it does not hold. Up
to now the batch could only put the triple in the manifest's `protocol` as a
free-text `instrument_ref`, because there was nothing to point at: the verdicts
carried an item key that resolved to nothing. Registering this artifact is what
makes that key resolve, so every verdict row can carry a real
`instrument_version_id` and the criterion's text stops being a fact the ledger
has to take on trust.

PROJECT SLUG: `external-evals` (Matthew, 2026-09-05). The eval is conceptually
the external OpenAI HealthBench one; the 610-prompt psych SUBSET is our
contribution, and the platform holds no `healthbench-psych` project. The
subset's identity travels in `description` and in `source`, not in the slug.

KIND: `rubric_item`, matching what `export_ledger_batch.py` writes on every
verdict. The shipped platform fixture
(`packages/artifact-schemas/fixtures/instrument-v1.restricted.json`) uses
`healthbench-psych-rubric` as an illustration; the batch is the consumer here
and the batch says `rubric_item`, so that is the key the two sides agree on.

VERSION: `v1.0.0` -- the release, not the corpus date. `versioning.md` freezes
v1.0.0 (610 prompts, `prompt_id_sha256 = 3788760429bb...`) for the duration of
PLOS review, and v1.1.0 adds two candidate MODELS against that unchanged subset
and unchanged rubric. Both grade runs are therefore cast against this one
instrument version; a version bump here would mean the RUBRIC moved, which is
a 2.x event (admitting the round-2 control item), not a 1.x one.

TEXT IS KEPT, AND GATED. Criterion text is OpenAI's, and not ours to publish --
but `visibility: restricted` is the platform's egress gate, not a redaction
(design §4): the text ships inline, `text_sha256` is computed at promotion, and
the column keeps it off every public, unauthenticated surface while serving it
in full to a spoke that runs the eval. Hashing the text away instead would have
lost exactly the material the platform exists to hold.

WHAT AN ITEM CARRIES. Everything about a criterion that is TRUE OF THE
CRITERION rather than of a verdict: its text, its points, its tags. Those are
the 312 bytes of `extra` that used to be copied onto each of 464,000 verdict
rows (the platform's seam note, "Row hygiene"); stated once here, they are
stated 464,000 times less. A verdict keeps only `item_key`, `item_ordinal` and
the `item_points` the ledger copies at write time so a score recomputes without
a join.

ITEM KEYS ARE MINTED, NOT FOUND. `hb_oss.jsonl` stores a prompt's rubric as a
POSITIONAL array with no per-criterion id, so the key is minted from the
position: `hb:<prompt_id>#<i>` -- byte-identical to what
`export_ledger_batch.py` mints for the verdict at the same position. `ordinal`
is that same `i`: presentation order WITHIN the prompt, never an identity.
Positional keying across two files is the failure mode this whole contract
exists to end, so the two must be generated by the same rule; they are, and
step 2 of this work verifies it against the rows already in the ledger.

DETERMINISTIC: prompts in the subset file's own order, criteria in corpus
order, key order fixed in code, JSON written COMPACT (the type's ceiling is
4 MB and this payload is ~3.4 MB compact but ~4.1 MB pretty-printed -- the
whitespace alone would be the difference between fitting and not).

OUTPUT

    platform/out/ledger/instruments/rubric-v1.0.0.json

Import (the platform's generic instrument door; `--producer` is required
because instrument.v1 is multi-producer):

    npx tsx scripts/import/instrument.ts \\
        <file> --producer mindbench-ai/healthbench-psych --promote

Usage:
  python3 platform/export_ledger_instrument.py [--dry-run]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

RELEASE_ROOT = Path(__file__).resolve().parent.parent
DEV_ROOT = RELEASE_ROOT.parent / "healthbench-psych-dev"

# The instrument's identity on the platform, and the exact triple
# export_ledger_batch.py writes on every verdict row.
PROJECT_SLUG = "external-evals"
KIND = "rubric_item"
VERSION = "v1.0.0"

SUBSET_NAME = "healthbench-psych-v1"
SUBSET_FILE = RELEASE_ROOT / "eval" / "subsets" / f"{SUBSET_NAME}.json"
# The corpus, read from the dev checkout: the release checkout gitignores
# source/ (it is not ours to redistribute) and the two copies are the same
# bytes when both are present.
HB_SOURCE = DEV_ROOT / "source" / "hb_oss.jsonl"
SOURCE_PATH = "source/hb_oss.jsonl"
OUT_FILE = RELEASE_ROOT / "platform" / "out" / "ledger" / "instruments" / f"rubric-{VERSION}.json"

TITLE = "HealthBench-Psych v1.0.0 rubric (610-prompt subset of OpenAI HealthBench)"

# The README's own attribution line: HealthBench is OpenAI's, and this
# repository's vendored grader is reproduced from openai/simple-evals under
# MIT. The criteria below come from that corpus; the SELECTION of the 610
# prompts is ours, and is what `source.commit` pins.
SOURCE_REPO = "openai/simple-evals"
LICENSE_NOTE = (
    "HealthBench and simple-evals are Copyright (c) 2024 OpenAI, released under the MIT "
    "License (THIRD-PARTY-NOTICES.md; full text at "
    "https://github.com/openai/simple-evals/blob/main/LICENSE). The criterion text below is "
    "OpenAI's corpus, downloaded by each user rather than redistributed by this repository "
    "(README, 'Reproducing'), which is why this version is held at visibility `restricted`: "
    "the text is kept in full for the spokes that run the eval and never reaches a public "
    "surface. The 610-prompt selection, and this instrument's item keys, are MindBench.ai's "
    "and are pinned by source.commit."
)

# Every verdict in this benchmark is a criteria_met boolean, so every item is.
VALUE_TYPE = "bool"


def git_commit(root: Path) -> str | None:
    """The checkout's HEAD, or None -- the same never-raises posture the other
    two exporters take: a checkout without git is a missing provenance field,
    not a failed export."""
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=root,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return None


def prompt_id_sha256(prompt_ids) -> str:
    """The benchmark's identity, as versioning.md defines it: sha256 over the
    JSON of the SORTED prompt-id list. Same function as
    export_ledger_batch.py's, deliberately -- an instrument that claimed the
    frozen hash under a different rule would be worse than one that claimed
    none."""
    return hashlib.sha256(json.dumps(sorted(prompt_ids)).encode("utf-8")).hexdigest()


def load_subset() -> dict:
    """The subset file, with its own recorded hash re-derived and checked."""
    meta = json.loads(SUBSET_FILE.read_text(encoding="utf-8"))
    recomputed = prompt_id_sha256(meta["prompt_ids"])
    if recomputed != meta["prompt_id_sha256"]:
        raise SystemExit(
            f"{SUBSET_FILE.name}: recorded prompt_id_sha256 "
            f"{meta['prompt_id_sha256'][:16]}... does not describe its own "
            f"prompt_ids ({recomputed[:16]}...) -- the subset file is inconsistent"
        )
    if len(set(meta["prompt_ids"])) != len(meta["prompt_ids"]):
        raise SystemExit(f"{SUBSET_FILE.name}: prompt_ids contains duplicates")
    return meta


def load_rubrics(prompt_ids: set[str]) -> dict[str, list[dict]]:
    """prompt_id -> the corpus's positional rubric array, for the subset only.

    Unlike export_ledger_batch.py, this reader KEEPS the criterion text: that
    text is the instrument."""
    if not HB_SOURCE.exists():
        raise SystemExit(
            f"{HB_SOURCE} is missing -- the rubric text comes from the HealthBench "
            f"corpus; see the README's 'Reproducing' section for the download"
        )
    rubrics: dict[str, list[dict]] = {}
    with HB_SOURCE.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            row = json.loads(line)
            if row["prompt_id"] in prompt_ids:
                rubrics[row["prompt_id"]] = row["rubrics"]
    missing = prompt_ids - set(rubrics)
    if missing:
        raise SystemExit(
            f"{len(missing)} of the subset's prompts have no rubric in "
            f"{HB_SOURCE.name} -- refusing to register an instrument with holes in it"
        )
    return rubrics


def build_items(subset: dict, rubrics: dict[str, list[dict]]) -> list[dict]:
    """One item per criterion, prompts in the subset file's own order and
    criteria in corpus order.

    `item_key` and `ordinal` are minted by exactly the rule
    export_ledger_batch.py mints a verdict's `item_key` and `item_ordinal` by:
    `hb:<prompt_id>#<i>` and `i`, the criterion's position in the prompt's
    array. Nothing else in either file establishes the correspondence, so the
    rule is the contract."""
    items: list[dict] = []
    seen: set[str] = set()
    for pid in subset["prompt_ids"]:
        for i, criterion in enumerate(rubrics[pid]):
            key = f"hb:{pid}#{i}"
            if key in seen:
                raise SystemExit(
                    f"duplicate item_key {key} -- an instrument resolves a verdict BY "
                    f"this key, so two items may never share one"
                )
            seen.add(key)
            item = {
                "item_key": key,
                # Presentation order within the prompt, not an identity: the
                # schema says so and the keying bug this contract ends is
                # exactly the mistake of treating position as identity.
                "ordinal": i,
                # Kept, not hashed away. `visibility` below is what gates it,
                # and `text_sha256` is computed by the promoter from this text.
                "text": criterion["criterion"],
                "points": criterion["points"],
                # An instrument-level fact (`level:`, `axis:`, `cluster:`),
                # which is why it is here once instead of on 464,000 verdicts.
                "tags": list(criterion.get("tags") or []),
                "value_type": VALUE_TYPE,
            }
            items.append(item)
    return items


def build_payload(subset: dict, items: list[dict], commit: str | None) -> dict:
    hash_hex = subset["prompt_id_sha256"]
    description = (
        f"The {len(items)} physician-written HealthBench rubric criteria covering the "
        f"{subset['n']} conversations of {SUBSET_NAME}, the mental-health subset of OpenAI's "
        f"HealthBench OSS corpus (2025-05-07 release, {SOURCE_PATH}). Frozen release "
        f"{VERSION}: prompt_id_sha256={hash_hex}. Items are keyed hb:<prompt_id>#<i> by the "
        f"criterion's position in the corpus's positional rubric array -- the same rule "
        f"platform/export_ledger_batch.py mints a verdict's item_key by, so a verdict names "
        f"an item instead of an array position. Criterion text is OpenAI's and is held at "
        f"visibility `restricted`; the subset selection is MindBench.ai's."
    )
    return {
        "schema_version": 1,
        "project_slug": PROJECT_SLUG,
        "kind": KIND,
        "version": VERSION,
        "title": TITLE,
        "description": description,
        # The gate, not a redaction: held in full, served to a spoke that runs
        # the eval, never to a public surface.
        "visibility": "restricted",
        "source": {
            "repo": SOURCE_REPO,
            "path": SOURCE_PATH,
            # The SPOKE's HEAD: what pins which 610 prompts these criteria
            # cover, which is the part of this instrument that is ours.
            "commit": commit,
            "license_note": LICENSE_NOTE,
        },
        "items": items,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dry-run", action="store_true", help="count everything, write nothing")
    args = ap.parse_args()

    subset = load_subset()
    subset_ids = set(subset["prompt_ids"])
    rubrics = load_rubrics(subset_ids)
    commit = git_commit(RELEASE_ROOT)

    print(f"healthbench-psych rubric -> instrument.v1 {PROJECT_SLUG}/{KIND}@{VERSION}")
    print(f"  subset {SUBSET_NAME}: n={len(subset_ids)}, "
          f"prompt_id_sha256 {subset['prompt_id_sha256'][:12]}...")
    print(f"  source {SOURCE_REPO} {SOURCE_PATH} @ spoke commit {commit}")

    items = build_items(subset, rubrics)

    # The identity check versioning.md asks for, over the ids the instrument
    # ACTUALLY covers rather than over the file that claims them. A membership
    # change is a major version event; an instrument that quietly shipped one
    # would silently re-point every verdict in the ledger.
    covered = {item["item_key"].split("#", 1)[0][len("hb:"):] for item in items}
    recomputed = prompt_id_sha256(covered)
    if recomputed != subset["prompt_id_sha256"]:
        raise SystemExit(
            f"prompt_id_sha256 of the covered ids ({recomputed[:16]}...) does not match "
            f"{SUBSET_FILE.name} ({subset['prompt_id_sha256'][:16]}...) -- the rubric "
            f"exported is not {SUBSET_NAME}'s, refusing to write"
        )
    print(f"  prompt_id_sha256 recomputed over {len(covered)} covered ids: matches")

    per_prompt = len(items) / len(covered)
    points = [item["points"] for item in items]
    print(f"  items: {len(items)} criteria, mean {per_prompt:.2f}/prompt, "
          f"points {min(points)}..{max(points)}, "
          f"{sum(1 for p in points if p < 0)} negative")

    payload = build_payload(subset, items, commit)
    # COMPACT, and measured from the bytes that will actually be written: the
    # type's ceiling is 4 MB and pretty-printing this payload crosses it.
    body = json.dumps(payload, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    print(f"  payload: {len(body)} bytes compact ({len(body) / 1024 / 1024:.2f} MB; ceiling 4 MB)")
    if len(body) > 4 * 1024 * 1024:
        raise SystemExit(
            f"payload is {len(body)} bytes, over instrument.v1's 4 MB ceiling -- "
            f"refusing to write an artifact the platform will not accept"
        )

    if args.dry_run:
        print("  dry run -- nothing written")
        return

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_bytes(body)
    print(f"  wrote {OUT_FILE}")
    print("  import:")
    print(f"    npx tsx scripts/import/instrument.ts {OUT_FILE} "
          f"--producer mindbench-ai/healthbench-psych --promote")


if __name__ == "__main__":
    main()
